F=imread('cameraman.tif');
figure;
imshow(F);
title('Original Image');
H = imnoise(F,'gaussian');
figure;
imshow(H);
title('Gaussian Noise');
M = imnoise(F,'salt & pepper');
figure;
imshow(M);
title('Salt & Pepper');
N = imnoise(F,'speckle');
figure;
imshow(N);
title('Speckle');
G = imgaussfilt(N,1);
figure;
imshow(G);
title('Gaussian Filtering');
I = medfilt2(M,[3 3]);
figure;
imshow(I);
title('Median Filtering');
K = wiener2(H,[3 3]);
figure;
imshow(K);
title('Wiener Filtering');